"""Utility helpers for the CLI Portify pipeline."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Signal Vocabulary (T03.11)
# ---------------------------------------------------------------------------

STEP_START: str = "step_start"
STEP_COMPLETE: str = "step_complete"
STEP_ERROR: str = "step_error"
STEP_TIMEOUT: str = "step_timeout"
GATE_PASS: str = "gate_pass"
GATE_FAIL: str = "gate_fail"

SIGNAL_VOCABULARY: tuple[str, ...] = (
    STEP_START,
    STEP_COMPLETE,
    STEP_ERROR,
    STEP_TIMEOUT,
    GATE_PASS,
    GATE_FAIL,
)


def parse_frontmatter(content: str) -> tuple[dict[str, Any], str]:
    """Parse YAML-style frontmatter from a Markdown string.

    Returns:
        (frontmatter_dict, body_string) — frontmatter dict is empty if
        the content does not start with '---'.
    """
    if not content.startswith("---"):
        return {}, content

    # Find the closing ---
    rest = content[3:]
    end_idx = rest.find("\n---")
    if end_idx == -1:
        return {}, content

    fm_text = rest[:end_idx].strip()
    body = rest[end_idx + 4:].lstrip("\n")

    fm: dict[str, Any] = {}
    for line in fm_text.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        # Type coercion: int, float, bool, string
        if val.lower() == "true":
            fm[key] = True
        elif val.lower() == "false":
            fm[key] = False
        else:
            try:
                fm[key] = int(val)
            except ValueError:
                try:
                    fm[key] = float(val)
                except ValueError:
                    fm[key] = val

    return fm, body


def verify_additive_only(original: str, updated: str) -> bool:
    """Verify that updated content only adds to original (no removals).

    Returns True if every line in original appears in updated.
    """
    original_lines = set(original.splitlines())
    updated_lines = set(updated.splitlines())
    return original_lines.issubset(updated_lines)


def count_lines(path: Path) -> int:
    """Count non-empty lines in a file."""
    try:
        text = path.read_text(errors="replace")
        return len(text.splitlines())
    except OSError:
        return 0


def is_portified_module(init_path: Path) -> bool:
    """Check whether an __init__.py contains portification markers.

    Returns True if the file contains 'Generated by' or 'Portified from'.
    """
    try:
        text = init_path.read_text(errors="replace")
        return "Generated by" in text or "Portified from" in text
    except OSError:
        return False
