"""Workdir creation and portify-config.yaml emission.

T02.04: Creates .dev/portify-workdir/<cli_name>/ and emits portify-config.yaml
with all resolved paths from PortifyConfig.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from .models import PortifyConfig


def create_workdir(config: PortifyConfig, base: Optional[Path] = None) -> Path:
    """Create the pipeline working directory for a portify run.

    Creates: <base>/.dev/portify-workdir/<cli_name>/

    If base is None, uses the project root (detected from workflow_path).

    Returns the created workdir Path.
    """
    cli_name_kebab = config.derive_cli_name()
    cli_name_snake = config.to_snake_case(cli_name_kebab)

    if base is None:
        base = _detect_project_root(config.workflow_path)

    workdir = base / ".dev" / "portify-workdir" / cli_name_snake
    workdir.mkdir(parents=True, exist_ok=True)
    return workdir


def emit_portify_config_yaml(config: PortifyConfig, workdir: Path) -> Path:
    """Emit portify-config.yaml to the workdir with all resolved paths.

    Required fields per D-0008 spec:
      workflow_path, cli_name, output_dir, workdir_path
    """
    cli_name_kebab = config.derive_cli_name()
    cli_name_snake = config.to_snake_case(cli_name_kebab)
    resolved_workflow = str(config.resolve_workflow_path())
    output_dir = str(config.output_dir) if config.output_dir else ""

    yaml_content = f"""# portify-config.yaml — generated by cli-portify pipeline
# Resolved paths for: {cli_name_kebab}
workflow_path: {resolved_workflow}
cli_name: {cli_name_kebab}
cli_name_snake: {cli_name_snake}
output_dir: {output_dir}
workdir_path: {workdir}
dry_run: {str(config.dry_run).lower()}
debug: {str(config.debug).lower()}
max_turns: {config.max_turns}
stall_timeout: {config.stall_timeout}
"""

    yaml_path = workdir / "portify-config.yaml"
    yaml_path.write_text(yaml_content)
    return yaml_path


def _detect_project_root(workflow_path: Path) -> Path:
    """Walk up from workflow_path to find the project root.

    Heuristic: find a directory containing pyproject.toml or src/.
    Falls back to workflow_path.parent.parent.
    """
    search = workflow_path if workflow_path.is_dir() else workflow_path.parent
    for _ in range(8):
        if (search / "pyproject.toml").exists() or (search / "src").exists():
            return search
        parent = search.parent
        if parent == search:
            break
        search = parent
    return workflow_path.parent.parent if workflow_path.parent != workflow_path else workflow_path.parent
