"""Structural tests for Cleanup Audit generated pipeline.

Tests verify the generated pipeline architecture:
- Step graph completeness
- Gate definitions
- Model consistency
- Command registration

Generated by: sc-cli-portify
"""

import ast
from pathlib import Path

import pytest


BASE_DIR = Path("src/superclaude/cli/cleanup_audit")

EXPECTED_FILES = [
    "models.py",
    "gates.py",
    "prompts.py",
    "config.py",
    "monitor.py",
    "process.py",
    "executor.py",
    "tui.py",
    "logging_.py",
    "diagnostics.py",
    "commands.py",
    "__init__.py",
]


class TestModuleCompleteness:
    """Verify all 12 generated files exist and are valid Python."""

    @pytest.mark.parametrize("filename", EXPECTED_FILES)
    def test_file_exists(self, filename):
        assert (BASE_DIR / filename).exists(), f"Missing file: {filename}"

    @pytest.mark.parametrize("filename", EXPECTED_FILES)
    def test_file_ast_valid(self, filename):
        content = (BASE_DIR / filename).read_text()
        ast.parse(content)  # Raises SyntaxError if invalid


class TestStepGraph:
    """Verify step graph completeness and structure."""

    def test_step_count(self):
        """6 steps should be defined matching D-0026 spec."""
        from superclaude.cli.cleanup_audit.executor import _build_steps
        from superclaude.cli.cleanup_audit.config import load_cleanup_audit_config

        config = load_cleanup_audit_config(target=".", dry_run=True)
        steps = _build_steps(config)
        assert len(steps) == 6, f"Expected 6 steps, got {len(steps)}"

    def test_step_ids(self):
        """Step IDs should be G-001 through G-006."""
        from superclaude.cli.cleanup_audit.executor import _build_steps
        from superclaude.cli.cleanup_audit.config import load_cleanup_audit_config

        config = load_cleanup_audit_config(target=".", dry_run=True)
        steps = _build_steps(config)
        ids = [s.id for s in steps]
        assert ids == ["G-001", "G-002", "G-003", "G-004", "G-005", "G-006"]

    def test_all_steps_have_gates(self):
        """Every step should have a gate assigned."""
        from superclaude.cli.cleanup_audit.executor import _build_steps
        from superclaude.cli.cleanup_audit.config import load_cleanup_audit_config

        config = load_cleanup_audit_config(target=".", dry_run=True)
        steps = _build_steps(config)
        for step in steps:
            assert step.gate is not None, f"Step {step.id} missing gate"


class TestGateDefinitions:
    """Verify gate definitions match spec."""

    def test_all_gates_defined(self):
        from superclaude.cli.cleanup_audit.gates import ALL_GATES

        assert len(ALL_GATES) == 6
        for gid in ["G-001", "G-002", "G-003", "G-004", "G-005", "G-006"]:
            assert gid in ALL_GATES, f"Missing gate: {gid}"

    def test_gate_tiers(self):
        from superclaude.cli.cleanup_audit.gates import ALL_GATES

        expected_tiers = {
            "G-001": "LIGHT",
            "G-002": "STANDARD",
            "G-003": "STANDARD",
            "G-004": "STRICT",
            "G-005": "STRICT",
            "G-006": "STANDARD",
        }
        for gid, expected_tier in expected_tiers.items():
            assert ALL_GATES[gid].enforcement_tier == expected_tier

    def test_strict_gates_have_semantic_checks(self):
        from superclaude.cli.cleanup_audit.gates import ALL_GATES

        for gid in ["G-004", "G-005"]:
            gate = ALL_GATES[gid]
            assert gate.semantic_checks, f"STRICT gate {gid} missing semantic checks"


class TestModelConsistency:
    """Verify model classes are properly structured."""

    def test_config_extends_pipeline_config(self):
        from superclaude.cli.cleanup_audit.models import CleanupAuditConfig
        from superclaude.cli.pipeline.models import PipelineConfig

        assert issubclass(CleanupAuditConfig, PipelineConfig)

    def test_step_result_extends_step_result(self):
        from superclaude.cli.cleanup_audit.models import CleanupAuditStepResult
        from superclaude.cli.pipeline.models import StepResult

        assert issubclass(CleanupAuditStepResult, StepResult)

    def test_step_extends_step(self):
        from superclaude.cli.cleanup_audit.models import CleanupAuditStep
        from superclaude.cli.pipeline.models import Step

        assert issubclass(CleanupAuditStep, Step)

    def test_status_enum_values(self):
        from superclaude.cli.cleanup_audit.models import CleanupAuditStatus

        required = {"pending", "running", "pass", "halt", "timeout", "error", "skipped"}
        actual = {s.value for s in CleanupAuditStatus}
        assert required.issubset(actual)


class TestCommandRegistration:
    """Verify CLI command registration."""

    def test_command_group_importable(self):
        from superclaude.cli.cleanup_audit import cleanup_audit_group

        assert cleanup_audit_group is not None

    def test_command_group_is_click_group(self):
        import click
        from superclaude.cli.cleanup_audit import cleanup_audit_group

        assert isinstance(cleanup_audit_group, click.Group)

    def test_command_registered_in_main(self):
        from superclaude.cli.main import main as cli_main

        assert "cleanup-audit" in cli_main.commands

    def test_run_subcommand_exists(self):
        from superclaude.cli.cleanup_audit.commands import cleanup_audit_group

        assert "run" in cleanup_audit_group.commands
