"""CLI subcommand package for Cleanup Audit pipeline.

Portified from: sc-cleanup-audit-protocol
Generated by: sc-cli-portify

This module provides the `superclaude cleanup-audit` command group.
"""

from .commands import cleanup_audit_group

__all__ = ["cleanup_audit_group"]
